web:
    restart: always
    build: ./web
    expose:
        - "8000"
    links:
        - postgres:postgres
    volumes:
        - ./web:/usr/src/app
        - ./web/static:/usr/src/app/static
    env_file: .env
    environment:
        DEBUG: 'false'
    command: /usr/local/bin/gunicorn gyros_of_hummus.wsgi:application -w 2 -b :8000 --reload

nginx:
    restart: always
    build: ./nginx/
    ports: 
        - "80:80"
    volumes:
        - "/www/static"
    volumes_from:
        - web
    links:
        - web:web

postgres:
    restart: always
    image: postgres:latest
    ports:
        - "5432"
    volumes:
        - pgdata:/var/lib/postgresql/data